stoppagename ={
"stationgateno2": 1,
"chawkbazar": 2,
"pumpinghouse":3,
"p.n.bank": 4,
"s.n.banerjeeroad": 5,
"oldcourthousestreet":6,
"victoriahouse":7,
"laketown":8,
"b.b.d.bag":9,
"fourpointcrossing":10,
"dakbangalow":11,
"esplanade":12,
"gardenreachRoad":13,
"strandroad":14,
"airportgateno.1":15,
"saltlakedepot":16,
"parkcircus":17,
"judgecourtroad":18,
"dunlopbridge":19,
"collegesquare":20,
"chandnichawk":21,
"a.p.croad":22,
"vivekanandaroad":23,
"kalighatbridge":24,
"philipscomplex":25,
"ramlalbazar":26,
"tapsia":27,
"phulpukurroad":28,
"bandelroad":29,
"collegestreet":30,
"howrahjunction":31,

}