# Generated by Django 3.2.7 on 2021-09-08 07:38

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartingLocation', models.CharField(max_length=30)),
                ('EndLocation', models.CharField(max_length=30)),
            ],
            managers=[
                ('Bus_booking', django.db.models.manager.Manager()),
            ],
        ),
    ]
