# Generated by Django 3.2.7 on 2021-09-08 07:51

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('busbookreg', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateModel',
            new_name='Bus_booking',
        ),
        migrations.AlterModelManagers(
            name='bus_booking',
            managers=[
                ('Bus_book', django.db.models.manager.Manager()),
            ],
        ),
    ]
