# Generated by Django 3.2.7 on 2021-09-08 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busbookreg', '0003_alter_bus_booking_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bus_booking',
            managers=[
            ],
        ),
    ]
